### ISSUE TITLE
Получение эмбеддингов зданий и поиск дополнительных фич

### ISSUE THREAD

**Issue by Romankkl03** [citec-spbu/Smart-UAV-Return-GNSS-Station#5]
### Спринт 2
@VadB4r  (Вадим Баранов)
- [x] Просмотр документации ResNet
- [x] Просмотр документации Dinov2
- [x] Поиск иных моделей для получения эмбеддингов #3 
- [x] Предоставить сравнительный анализ моделей [плюсы/минусы] (GitHub/Notion) *Красивая табличка:)*
- [x] Создать пайплайн для получения эмбеддингов
- [x] Затестить получение эмбеддингов с геоподложки
- [x] Использование TripletLoss для сравнения эмбеддингов с камеры и с #2 
- [x] Получение общего пайплайна для камеры #3 + запушить ветку
- [x] обучить PCA для уменьшения размерности эмбеддингов
- [x] вставить PCA в пайплайн
- [x] написать написать интерфейс для получения новых эмб
